### ISSUE TITLE
Strange interaction with BetterFolders

### ISSUE THREAD

**Issue by kkiris** [Fibes1/discord-collapse#1]
The theme interacts strangely with server folders. Opening a server folder doesn't show the new icons immediately; instead one must collapse and re-open the server sidebar to see the folder contents. When one does this, only the folder contents are visible, other server icons do not appear. Vanilla behavior is that the folder contents appear in the same sidebar, below the folder icon, with all other server icons present. This affects Vencord on both Windows & Mac.

**Comment by Fibes1** [comment]
Do you use BetterFolders? I can only recreate this issue with the "Sidebar" setting from that plugin enabled.

If that's the case then I unfortunately don't plan to fix this, since there are a lot of weird issues that emerge from it that I haven't been able to fix in the past.

**Comment by kkiris** [comment]
That's totally my bad; I didn't even know I had BetterFolders enabled. Sorry for not checking that before making the issue.

**Comment by kkiris** [comment]
> Do you use BetterFolders? I can only recreate this issue with the "Sidebar" setting from that plugin enabled.
> 
> If that's the case then I unfortunately don't plan to fix this, since there are a lot of weird issues that emerge from it that I haven't been able to fix in the past.

will mark as not planned.
